install.packages('BiocManager')
install.packages("rmarkdown")
install.packages("survival")
install.packages("survminer")
install.packages("survivalROC")
install.packages("tibble")
install.packages("purrr")
install.packages("tidyr")
install.packages("dplyr")
install.packages("caTools")
install.packages("bitops")
install.packages("rprojroot")
install.packages("FactoMineR")
install.packages("XML", repos = "http://www.omegahat.net/R")
BiocManager::install('limma')
BiocManager::install("genefilter")

