install.packages("rmarkdown")
install.packages("limma")
install.packages("survival")
install.packages("survminer")
install.packages("curatedBreastData")
install.packages("survivalROC")
install.packages("tibble")
install.packages("purrr")
install.packages("tidyr")
install.packages("dplyr")
install.packages("caTools")
install.packages("bitops")
install.packages("rprojroot")

