install.packages('BiocManager')
install.packages("rmarkdown")
install.packages("limma")
install.packages("survival")
install.packages("survminer")
install.packages("survivalROC")
install.packages("tibble")
install.packages("purrr")
install.packages("tidyr")
install.packages("dplyr")
install.packages("caTools")
install.packages("bitops")
install.packages("rprojroot")
BiocManager::install('limma')
BiocManager::install("curatedBreastData")


